### ISSUE TITLE
has-error classes not removed on each submit

### ISSUE THREAD

**Issue by Roy-Orbison** [felixarntz/bootstrap-for-contact-form-7#52]
Causes inputs that were only initially incorrect to display as permanently incorrect.

**Comment by gidomanders** [comment]
Could you please be a little more specific? I tried to reproduce this problem without success. On every submit, the ``has-error`` class is removed from all ``form-group``s.

Maybe you have the ``form-group`` class on a tag that's not a ``div``? The ``has-error`` class is only being removed from ``div`` tags with class ``form-group``, because this plugin only creates ``div``s.

**Comment by lcdsantos** [comment]
Contact Form 7 refactored their JS in the recent versions and doesn't have the `$.fn.wpcf7ClearResponseOutput()` function anymore.

A quick workaround for now (until it gets fixed), is to use events:
```js
$('div.wpcf7').on('wpcf7beforesubmit', function() {
    $(this).wpcf7ClearResponseOutput();
});
```

**Comment by felixarntz** [comment]
The `wpcf7beforesubmit` JS event appears to no longer exist in CF7 version 5.0. A better approach would be to override the `wpcf7.clearResponse()` function. This also ensures there are no collisions with old version behavior.
